const ShortOverview = ({ title, info }) => {
  return (
    <div className="rounded-md bg-white p-4 shadow">
      <h2 className="mb-4 text-xl font-semibold text-gray-900">{title}</h2>
      <dl className="flex items-center justify-between gap-4">
        <dt className="text-base font-normal text-gray-500">Delivery Status</dt>
        <dd className="text-base font-medium capitalize text-gray-900">
          {info?.status}
        </dd>
      </dl>
      <dl className="flex items-center justify-between gap-4">
        <dt className="text-base font-normal text-gray-500">
          {info?.status === "delivered"
            ? "Delivered At"
            : "Expected Delivery Date"}
        </dt>
        <dd className="text-base font-medium capitalize text-gray-900">
          {info?.deliveredDate}
        </dd>
      </dl>
      {info?.paymentStatus && (
        <dl className="flex items-center justify-between gap-4">
          <dt className="text-base font-normal text-gray-500">
            Payment Status
          </dt>
          <dd className="text-base font-medium capitalize text-gray-900">
            {info?.paymentStatus}
          </dd>
        </dl>
      )}
      {info?.handleBy && (
        <dl className="flex items-center justify-between gap-4">
          <dt className="text-base font-normal text-gray-500">
            Quote Handle By
          </dt>
          <dd className="text-base font-medium capitalize text-gray-900">
            {info?.handleBy}
          </dd>
        </dl>
      )}
      {info?.paymentHandlerName && (
        <dl className="flex items-center justify-between gap-4">
          <dt className="text-base font-normal text-gray-500">
            Payment Handle By
          </dt>
          <dd className="text-base font-medium capitalize text-gray-900">
            {info?.paymentHandlerName}
          </dd>
        </dl>
      )}
      {info?.invoiceGeneratedBy && (
        <dl className="flex items-center justify-between gap-4">
          <dt className="text-base font-normal text-gray-500">
            Invoice Generated By
          </dt>
          <dd className="text-base font-medium capitalize text-gray-900">
            {info?.invoiceGeneratedBy}
          </dd>
        </dl>
      )}
    </div>
  );
};

export default ShortOverview;
